use_frameworks!

platform :ios, '9.0'

target 'GYAnimationRefresh_Example' do
  pod 'GYAnimationRefresh', :path => '../'
 
  target 'GYAnimationRefresh_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    
  end
  #动画
  pod 'lottie-ios', '2.5.2'
  # 布局
  pod 'Masonry'
end

